@node CfgGeneral
@section Configuration general options

Those options are in the root of configuration dictionary.

@verbatim
spool: /var/spool/nncp
log: /var/spool/nncp/log

# All of options below are optional
umask: "022"
noprogress: true
nohdr: true

# MultiCast Discovery
mcd-listen: ["em0", "igb1"]
mcd-send: {em0: 60, igb1: 5}
@end verbatim

@table @code
@item spool
Absolute path to the @ref{Spool, spool} directory.
@item log
Either:
    @itemize
    @item absolute path to the @ref{Log, log} file
    @item @code{FD:XXX}, where @code{XXX} is a decimal file descriptor
        to write records too
    @end itemize
@item umask
Will force all invoked commands to override their umask to specified
octal mask. Useful for using with @ref{Shared spool, shared spool directories}.
@item noprogress
When enabled, disables progress showing for many commands by default.
You can always force its showing with @option{-progress} command line
option anyway.
@anchor{CfgNoHdr}
@item nohdr
@strong{nohdr} option disables @ref{HdrFile, .hdr} files usage.
@end table

And optional @ref{MCD, MultiCast Discovery} options:

@table @code
@anchor{CfgMCDListen}
@item mcd-listen
Specifies list of network interfaces @ref{nncp-caller} will listen for
incoming @ref{MCD} announcements.
@anchor{CfgMCDSend}
@item mcd-send
Specifies list of network interfaces, and intervals in seconds, where
@ref{nncp-daemon} will send @ref{MCD} announcements.
@end table
