@node Об утилитах
@section Подробнее об утилитах NNCP

@verbatiminclude pedro.txt

@strong{NNCP} (Node to Node copy) это набор утилит упрощающий безопасный
обмен файлами, почтой и командами в режиме сохранить-и-переслать.

Эти утилиты предназначены помочь с построением однораговых
@url{https://ru.wikipedia.org/wiki/DTN, устойчивых к разрывам} сетей
небольшого размера (дюжины узлов), в режиме
@url{https://ru.wikipedia.org/wiki/Friend-to-friend, друг-к-другу} (F2F)
со статической маршрутизацией для безопасной надёжной передачи файлов,
запросов на передачу файлов, Интернет почты и команд по принципу
выстрелил-и-забыл. Все пакеты проверяются на целостность, шифруются по
принципу @url{https://en.wikipedia.org/wiki/End-to-end_encryption,
точка-точка}, аутентифицируются известными публичными ключами
участников.
@url{https://ru.wikipedia.org/wiki/Луковая_маршрутизация, Луковичное}
(onion) шифрование применяется ко всем ретранслируемым пакетам. Каждый
узел выступает одновременно в роли клиента и сервера, может использовать
как push, так и poll модель поведения.
А также есть поддержка @ref{Multicast, мультивещательной} рассылки пакетов.

Поддержка из коробки offline
@url{https://ru.wikipedia.org/wiki/Флоппинет, флоппинета},
@url{https://ru.wikipedia.org/wiki/Тайник, тайников}
для сброса информации (dead drop), последовательных и не перезаписываемых
@url{https://ru.wikipedia.org/wiki/CD-ROM, CD-ROM}/@url{https://ru.wikipedia.org/wiki/Стример, ленточных}
хранилищ, компьютеров с
@url{https://ru.wikipedia.org/wiki/Воздушный_зазор_(сети_передачи_данных), воздушным зазором}
(air-gap). Но также существует и online TCP демон с полнодуплексной
возобновляемой передачей данных.

Узнайте о возможных @ref{Сценарии, сценариях использования}!

NNCP это @url{https://www.gnu.org/philosophy/pragmatic.ru.html,
копилефт} @url{https://www.gnu.org/philosophy/free-sw.ru.html, свободное
программное обеспечение}: лицензировано под условиями
@url{https://www.gnu.org/licenses/gpl-3.0.ru.html, GNU GPLv3}. Оно
должно работать на всех @url{https://ru.wikipedia.org/wiki/POSIX,
POSIX}-совместимых системах. Лёгкая @ref{Integration, интеграция} с
существующими @url{https://ru.wikipedia.org/wiki/SMTP, SMTP} серверами.
Единственный конфигурационный @url{https://hjson.github.io/, Hjson} файл.

Зачем создавать ещё одно решение с принципом сохранить-и-переслать когда
уже существуют UUCP, FTN и даже SMTP? Посмотрите @ref{Сравнение, сравнение}!
Простота, криптографическая безопасность, совместимость с флоппинетом и
лёгкая интеграция с существующими SMTP серверами -- вот и причины.
