@node Dependencies
@cindex dependencies
@subsection Dependencies

@multitable @columnfractions .50 .50
@headitem Library @tab Licence
@item @code{github.com/davecgh/go-xdr} @tab ISC
@item @code{github.com/dustin/go-humanize} @tab Expat
@item @code{github.com/flynn/noise} @tab BSD 3-Clause
@item @code{github.com/fsnotify/fsnotify} @tab BSD 3-Clause
@item @code{github.com/gorhill/cronexpr} @tab GNU GPLv3
@item @code{github.com/gosuri/uilive} @tab Expat
@item @code{github.com/hjson/hjson-go} @tab Expat
@item @code{github.com/klauspost/compress} @tab BSD 3-Clause
@item @code{github.com/klauspost/cpuid} @tab BSD 3-Clause
@item @code{github.com/quic-go/quic-go} @tab Expat
@item @code{go.cypherpunks.ru/balloon} @tab GNU LGPLv3
@item @code{go.cypherpunks.su/recfile/v3} @tab GNU GPLv3
@item @code{golang.org/x/crypto} @tab BSD 3-Clause
@item @code{golang.org/x/net} @tab BSD 3-Clause
@item @code{golang.org/x/sys} @tab BSD 3-Clause
@item @code{golang.org/x/term} @tab BSD 3-Clause
@item @code{golang.org/x/time} @tab BSD 3-Clause
@item @code{lukechampine.com/blake3} @tab Expat
@end multitable

And additional ones for Yggdrasil support:

@multitable @columnfractions .50 .50
@headitem Library @tab Licence
@item @code{github.com/Arceliar/ironwood} @tab MPLv2
@item @code{github.com/Arceliar/phony} @tab MPLv2
@item @code{github.com/gologme/log} @tab BSD 3-Clause
@item @code{github.com/google/btree} @tab Apache 2.0
@item @code{github.com/huandu/xstrings} @tab Expat
@item @code{github.com/yggdrasil-network/yggdrasil-go} @tab GNU LGPLv3
@item @code{golang.org/x/term} @tab BSD 3-Clause
@item @code{gvisor.dev/gvisor} @tab Apache 2.0
@end multitable
