@node Tarballs
@section Prepared tarballs

You can obtain releases source code prepared tarballs from the links below
(or use @url{https://sourceforge.net/projects/nncp/files/, Sourceforge mirror}).
Do not forget to check tarball @ref{Integrity, integrity}.

Tarballs include all necessary required libraries:

@multitable @columnfractions .50 .50
@headitem Library @tab Licence
@item @code{github.com/dustin/go-humanize} @tab MIT
@item @code{github.com/flynn/noise} @tab BSD 3-Clause
@item @code{github.com/go-check/check} @tab BSD 2-Clause
@item @code{github.com/go-yaml/yaml} @tab Apache License 2.0 and MIT
@item @code{github.com/gorhill/cronexpr} @tab GNU GPLv3
@item @code{github.com/minio/blake2b-simd} @tab Apache License 2.0
@item @code{golang.org/x/crypto} @tab BSD 3-Clause
@item @code{golang.org/x/net} @tab BSD 3-Clause
@item @code{golang.org/x/sys} @tab BSD 3-Clause
@end multitable

@multitable {XXXXX} {XXXX KiB} {link sign} {xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
@headitem Version @tab Size @tab Tarball @tab SHA256 checksum

@item @ref{Release 0.6, 0.6} @tab 746 KiB
@tab @url{download/nncp-0.6.tar.xz, link} @url{download/nncp-0.6.tar.xz.sig, sign}
@tab @code{DCFEE3F9 F669AC28 563C50DB 67BB8B43 0CFF4AB6 EC770ACE B5378D0B B40C0656}

@item @ref{Release 0.5, 0.5} @tab 743 KiB
@tab @url{download/nncp-0.5.tar.xz, link} @url{download/nncp-0.5.tar.xz.sig, sign}
@tab @code{D98F9149 5A6D6726 4C659640 1AD7F400 271A58CE 5D8D4AC5 5D1CF934 59BEDFA6}

@item @ref{Release 0.4, 0.4} @tab 741 KiB
@tab @url{download/nncp-0.4.tar.xz, link} @url{download/nncp-0.4.tar.xz.sig, sign}
@tab @code{93577327 B3DEBFE3 A80BEB0D 8325B2E6 0939EC55 4DBB05F3 4CA34B99 229C3722}


@item @ref{Release 0.3, 0.3} @tab 741 KiB
@tab @url{download/nncp-0.3.tar.xz, link} @url{download/nncp-0.3.tar.xz.sig, sign}
@tab @code{6E76EC5E 6B575C65 BF2D6388 870F2A1C 417D63E4 1628CAA1 BB499D0D 0634473B}

@item @ref{Release 0.2, 0.2} @tab 740 KiB
@tab @url{download/nncp-0.2.tar.xz, link} @url{download/nncp-0.2.tar.xz.sig, sign}
@tab @code{00BEAC5A 0C4083B0 42E3152B ACA6FF20 12768B82 CE24D716 8E04279C ECE14DB7}

@item 0.1 @tab 720 KiB
@tab @url{download/nncp-0.1.tar.xz, link} @url{download/nncp-0.1.tar.xz.sig, sign}
@tab @code{8F71D65B 70865EBF FE802CDF A5C14D00 A9FD6559 FD722E60 5D97E82C 5E2412C2}

@end multitable
