@node Installation
@unnumbered Installation

NNCP should run on any POSIX-compatible operating system with file
systems supporting directory and filename's length up to 57 characters.

NNCP is written on @url{https://golang.org/, Go} programming language
and you have to install Go compiler (1.7+ version is highly
recommended). @emph{Make} (BSD and GNU ones are fine) is recommended for
convenient building. @url{https://www.gnu.org/software/texinfo/,
Texinfo} is used for building documentation.

In general you must get @ref{Tarballs, the tarball}, check its
@ref{Integrity, integrity and authenticity} and run @command{make}.
Look for general and @ref{Platform-specific, platform-specific}
installation instructions.

@menu
* Prepared tarballs: Tarballs.
* Tarballs integrity check: Integrity.
* Platform-specific instructions: Platform-specific.
* Development source code: Sources.
@end menu

@include download.texi
@include integrity.texi
@include platforms.texi
@include sources.texi
