@node Integrity
@cindex integrity check
@cindex authenticity check
@cindex OpenSSH
@section Tarballs integrity check

You @strong{have to} verify downloaded tarballs authenticity to be sure
that you retrieved trusted and untampered software.

@url{https://www.openssh.com/, OpenSSH} @file{.sig} signature,
@url{PUBKEY-SSH.pub, public key} and its LibrePGP
@url{PUBKEY-SSH.pub.asc, signature}.
Its fingerprint: @code{SHA256:u1fC9fUIJnQOm+/5oZj94Xn6j76W2nm7hRlPFzpfJdk}.

@example
$ ssh-keygen -Y verify -f PUBKEY-SSH.pub -I releases@@nncpgo.org -n file \
    -s nncp-@value{VERSION}.tar.xz.sig <nncp-@value{VERSION}.tar.xz
@end example

@url{http://www.keks.stargrave.org/cm/index.html, KEKS/CM} @file{.cm}
quantum resistant SLH-DSA signature,
@url{PUBKEY-CM.pub, public key} and its LibrePGP
@url{PUBKEY-CM.pub.asc, signature}.

@example
$ fpr=$(kekspp -v -p /data/id <PUBKEY-CM.pub)
$ echo $fpr
54D487664D5C19FE8C63F690155381AD4B0102EB6B9DF5A8DAD7A3B339610608
$ mkdir -p pubs
$ ln -s ../PUBKEY-CM.pub pubs/$fpr
$ cat nncp-$v.tar.xz.cm nncp-$v.tar.xz | cmsigtool -v -d -pubs pubs
@end example
