@node Новости
@section Новости

@node Релиз 0.9
@subsection Релиз 0.9
@itemize
@item
Исправлена обработка @option{-rx}/@option{-tx} опций @command{nncp-call}
команды. Они игнорировались.
@end itemize

@node Релиз 0.8
@subsection Релиз 0.8
@itemize
@item
Небольшое исправление ошибки в команде @command{nncp-file}, где опция
@option{-minsize} для передачи без разбиения на части была в байтах, а
не KiB-ах.
@end itemize

@node Релиз 0.7
@subsection Релиз 0.7
@itemize
@item
Возможность предоставлять данные для @command{nncp-file} через
стандартный ввод, используя временный зашифрованный файл для этого.

@item
Появилась возможность передачи файлов разбитых на части, с сопутствующей
@command{nncp-reass} командой и @option{freqchunked} опцией
конфигурационного файла. Полезно для передачи больших файлов через
маленькие устройства хранения.

@item
@option{freqminsize} опция конфигурационного файла, аналогичная
@option{-minsize}.

@item
Опция @option{-force} команды @command{nncp-xfer} переименована в
@option{-mkdir} для ясности.

@item
Опция @option{-minsize} задётся в KiB, а не байтах, для удобства.

@item
Команда @command{nncp-newcfg} переименована в @command{nncp-cfgnew},
а @command{nncp-mincfg} в @command{nncp-cfgmin}, для того чтобы они
имели общий префикс и были сгруппированы для удобства.

@item Появилась команда @command{nncp-cfgenc}, позволяющая
шифровать/дешифровать конфигурационный файл, чтобы безопасно его хранить
без использования OpenPGP или других подобных инструментов.

@item
Обновлены зависимые криптографические библиотеки.
@end itemize

@node Релиз 0.6
@subsection Релиз 0.6
@itemize
@item Появилась небольшая команда @command{nncp-rm}.
@item Обновлены зависимые криптографические библиотеки.
@end itemize

@node Релиз 0.5
@subsection Релиз 0.5
@itemize
@item Тривиальное небольшое исправление в значениях приоритетов
по-умолчанию в @command{nncp-file} и @command{nncp-freq} командах.
@end itemize

@node Релиз 0.4
@subsection Релиз 0.4
@itemize
@item Небольшое исправление в @command{nncp-call}, @command{nncp-caller},
@command{nncp-daemon}: иногда они могли падать с segmentation fault
ошибкой (данные не терялись).
@item @command{nncp-newnode} переименована в @command{nncp-newcfg} --
это короче и удобнее для использования.
@item Появилась команда @command{nncp-mincfg}: вспомогательная утилита
позволяющая создать минималистичный урезанный конфигурационный файл без
приватных ключей, что полезно во время использования @command{nncp-xfer}.
@end itemize

@node Релиз 0.3
@subsection Релиз 0.3
Исправлена совместимость с Go 1.6.

@node Релиз 0.2
@subsection Релиз 0.2
@itemize
@item @strong{Несовместимое} изменение формата пакета (магическое число
тоже изменено): поле размера пакета шифруется и не посылается в открытом
виде.
@item @option{-minsize} опция даёт возможность автоматически дополнять
исходящие пакеты до указанного минимального размера.
@item @command{nncp-daemon} и
@command{nncp-call}/@command{nncp-caller} всегда в фоне проверяют появление
исходящих @emph{tx} пакетов пока подключены. Удалённая сторона сразу же
оповещается об этом.
@item @option{-onlinedeadline} опция даёт возможность выставления
timeout-а на неактивность в online соединении, когда оно должно быть
отключено. Она может быть использована для сохранения соединения на
долгое время.
@item @option{-maxonlinetime} опция даёт возможность указания
максимального возможного времени жизни соединения.
@item Появилась @command{nncp-caller} команда: клиент TCP-демона
работающий по cron-у.
@item @command{nncp-pkt} команда может разжимать данные.
@end itemize
