@node News
@unnumbered News

@node Release 0.2
@section Release 0.2
@itemize
@item @strong{Incompatible} packet's format change (magic number is
changed too): size field is encrypted and is not send in plaintext
anymore.
@item @option{-minsize} option gives ability to automatically pad
outgoing packets to specified minimal size.
@item @ref{nncp-daemon} and @ref{nncp-call}/@ref{nncp-caller} always
check new @emph{tx} packets appearance in the background while
connected. Remote side is immediately notified.
@item @option{-onlinedeadline} option gives ability to configure timeout
of inactivity of online connection, when it could be disconnected. It
could be used to keep connection alive for a long time.
@item @option{-maxonlinetime} option gives ability to set maximal
allowable online connection aliveness time.
@item @ref{nncp-caller} command appeared: cron-ed TCP daemon caller.
@item @ref{nncp-pkt} command can decompress the data.
@end itemize

@node Release 0.3
@section Release 0.3
Fixed compatibility with Go 1.6.
