@node Sources
@section Development source code

Development source code contains the latest version of the code. It may
be buggy. It does not contain compiled documentation and dependent
libraries source code. Because of that, it is recommended for porters
to use @ref{Tarballs, tarballs} instead.

You can obtain it by cloning @url{http://git-scm.com/, Git}
@url{http://git.cypherpunks.ru/cgit.cgi/nncp.git/log/, repository}
and fetching dependent libraries source code as git submodules:

@verbatim
% git clone git://git.cypherpunks.ru/nncp.git nncp
% cd nncp
% git checkout develop
% git submodule update --init
@end verbatim

Github.com mirror exists: @url{https://github.com/stargrave/nncp}.
