@node Sync
@unnumbered Sync protocol

So-called sync protocol is used in current TCP daemon's implementation.
It is aimed to be very simple and effective. It is used over reliable
transport like TCP connections.

It must be effective both on single-duplex and full-duplex links (for
example satellites have very high throughput, but high-delay links).
Acknowledging of each received packet, like
@url{https://en.wikipedia.org/wiki/XMODEM, XMODEM} does, causes
unacceptable performance degradation.

TODO

http://noiseprotocol.org/noise.html#interactive-patterns
